package org.motechproject.openmrs.atomfeed.service;

import org.motechproject.MotechException;
import org.motechproject.openmrs.atomfeed.events.EventDataKeys;

/**
 * AtomFeedClient allow users to fetch an atom provided by the OpenMRS Atom Feed module If the atom feed contains new
 * entries, corresponding events will be raised in the Motech server that correspond to those actions.
 * 
 * Clients interested in listening for events should see {@link EventDataKeys} for a full description of possible events
 * that may be generated by the Atom Feed.
 */
public interface AtomFeedService {

    /**
     * Fetches the Atom Feed from the OpenMRS
     * 
     * @throws MotechException
     *             If there was a problem fetching the openmrs atom feed
     */
    void fetchAllOpenMrsChanges();

    /**
     * Fetch changes from the OpenMRS Atom Feed, and retrieve only changes that have occurred since the atom feed was
     * last checked
     */
    void fetchOpenMrsChangesSinceLastUpdate();

    /**
     * Fetch changes from the OpenMRS Atom Feed since <code>sinceDateTime</code>. If <code>sinceDateTime</code> is null,
     * retrieve all entries
     * 
     * @param sinceDateTime A date time formatted as: 2012-07-09T13:55:35
     */
    void fetchOpenMrsChangesSince(String sinceDateTime, String lastId);
}
